#### Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Read data

In [3]:
col_names = ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
data = pd.read_csv("imports-85.csv", names=col_names)

#### Data cleaning

In [7]:
data.shape

(205, 26)

In [7]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [8]:
#List of columns that contain a "?" for missing data
colslist = list(data.columns)
for col in colslist:
    if('?' in data[col].value_counts()):
        print(col + " - " + str(data[col].value_counts()['?']))

normalized-losses - 41
num-of-doors - 2
bore - 4
stroke - 4
horsepower - 2
peak-rpm - 2
price - 4

##### Handle missing values

- num-of-doors

In [9]:
data.loc[data["num-of-doors"]=="?"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
27,1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102,5500,24,30,8558
63,0,?,mazda,diesel,std,?,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.7,64,4650,36,42,10795

In [10]:
# Are there any two door sedans?
data.loc[data["body-style"]=="sedan"]["num-of-doors"].value_counts()

num-of-doors
four    79
two     15
?        2
Name: count, dtype: int64

In [11]:
data.loc[(data["make"]=="dodge")&(data["body-style"]=="sedan")]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6692
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,7609
27,1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102,5500,24,30,8558

In [12]:
data.loc[(data["make"]=="mazda")&(data["body-style"]=="sedan")]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
53,1,113,mazda,gas,std,four,sedan,fwd,front,93.1,...,91,2bbl,3.03,3.15,9.0,68,5000,31,38,6695
54,1,113,mazda,gas,std,four,sedan,fwd,front,93.1,...,91,2bbl,3.08,3.15,9.0,68,5000,31,38,7395
60,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,8495
62,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10245
63,0,?,mazda,diesel,std,?,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.7,64,4650,36,42,10795
65,0,118,mazda,gas,std,four,sedan,rwd,front,104.9,...,140,mpfi,3.76,3.16,8.0,120,5000,19,27,18280
66,0,?,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72,4200,31,39,18344

In [13]:
data["num-of-doors"].value_counts()

num-of-doors
four    114
two      89
?         2
Name: count, dtype: int64

In [14]:
num_doors=data["num-of-doors"].mode()

In [15]:
# replace "?" by four because all mazda and dodge sedans have four doors
data["num-of-doors"]=data["num-of-doors"].replace("?",num_doors.iloc[0])

In [16]:
# convert num-of-doors to numeric format
def convert_num_doors (doorstr):
    if(doorstr == 'two'):
       return 2 
    if (doorstr =='four'):
       return 4
    return 0

data["num-of-doors"] = data["num-of-doors"].apply(lambda x: convert_num_doors (x))

- bore and stroke

In [17]:
data.loc[data["bore"]=="?"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
55,3,150,mazda,gas,std,2,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,10945
56,3,150,mazda,gas,std,2,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,11845
57,3,150,mazda,gas,std,2,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,13645
58,3,150,mazda,gas,std,2,hatchback,rwd,front,95.3,...,80,mpfi,?,?,9.4,135,6000,16,23,15645

In [18]:
data.loc[(data["make"]=="mazda")&(data["body-style"]=="hatchback"), ["fuel-type", "bore","stroke", "horsepower"]]

   fuel-type  bore stroke horsepower
50       gas  3.03   3.15         68
51       gas  3.03   3.15         68
52       gas  3.03   3.15         68
55       gas     ?      ?        101
56       gas     ?      ?        101
57       gas     ?      ?        101
58       gas     ?      ?        135
59       gas  3.39   3.39         84
61       gas  3.39   3.39         84
64       gas  3.39   3.39         84

In [19]:
# remove bore and stroke columns - because there is not enough information available to replace the nan values
# bore and stroke are engine design which is information related to other resources
data = data.drop("bore", axis=1)
data = data.drop("stroke", axis=1)

- horsepower

In [20]:
data.loc[data["horsepower"]=="?"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
130,0,?,renault,gas,std,4,wagon,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9295
131,2,?,renault,gas,std,2,hatchback,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9895

In [23]:
data.loc[(data["make"]=="renault")]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
130,0,?,renault,gas,std,4,wagon,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9295
131,2,?,renault,gas,std,2,hatchback,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9895

In [22]:
# check if there are other car models that have the same specification
data.loc[(data["compression-ratio"]==8.7)&(data["engine-size"]==132)&(data["num-of-cylinders"]=="four")]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
130,0,?,renault,gas,std,4,wagon,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9295
131,2,?,renault,gas,std,2,hatchback,fwd,front,96.1,...,ohc,four,132,mpfi,8.7,?,?,23,31,9895

In [24]:
# remove missing values - there are no other horsepower values for the Renault brand to compare
# there is no more renault in the dataset
data = data[~data['horsepower'].str.contains('\?')]

- price

In [26]:
# three brands with missing prices
data.loc[data["price"]=="?"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
9,0,?,audi,gas,turbo,2,hatchback,4wd,front,99.5,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?
44,1,?,isuzu,gas,std,2,sedan,fwd,front,94.5,...,ohc,four,90,2bbl,9.6,70,5400,38,43,?
45,0,?,isuzu,gas,std,4,sedan,fwd,front,94.5,...,ohc,four,90,2bbl,9.6,70,5400,38,43,?
129,1,?,porsche,gas,std,2,hatchback,rwd,front,98.4,...,dohcv,eight,203,mpfi,10.0,288,5750,17,28,?

In [139]:
# isuzu brand
# remove missing values - not enough price sample to infer on isuzu brand
data.loc[data["make"]=="isuzu"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
43,0,?,isuzu,gas,std,4,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.5,78,4800,24,29,6785
44,1,?,isuzu,gas,std,2,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
45,0,?,isuzu,gas,std,4,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
46,2,?,isuzu,gas,std,2,hatchback,rwd,front,96.0,...,119,spfi,3.43,3.23,9.2,90,5000,24,29,11048

In [167]:
# audi brand
# remove missing values - there are no other samples similar to the nan type
data.loc[data["make"]=="audi"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,4,sedan,fwd,front,99.8,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,4,sedan,4wd,front,99.4,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,2,sedan,fwd,front,99.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,4,sedan,fwd,front,105.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,4,wagon,fwd,front,105.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,4,sedan,fwd,front,105.8,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,2,hatchback,4wd,front,99.5,...,ohc,five,131,mpfi,7.0,160,5500,16,22,?

In [168]:
'''
- porsche brand
- remove missing values - there is only one sample with the same body-style, 
but differs in other features
'''
data.loc[data["make"]=="porsche"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
125,3,186,porsche,gas,std,2,hatchback,rwd,front,94.5,...,ohc,four,151,mpfi,9.5,143,5500,19,27,22018
126,3,?,porsche,gas,std,2,hardtop,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,32528
127,3,?,porsche,gas,std,2,hardtop,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,34028
128,3,?,porsche,gas,std,2,convertible,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,37028
129,1,?,porsche,gas,std,2,hatchback,rwd,front,98.4,...,dohcv,eight,203,mpfi,10.0,288,5750,17,28,?

In [41]:
# drop missing values from price column
data = data[~data['price'].str.contains('\?')]

- normalized-losses

In [43]:
data.loc[data["normalized-losses"]=="?"]["make"].value_counts()

make
bmw              4
peugot           4
volkswagen       4
alfa-romero      3
mercedes-benz    3
mitsubishi       3
porsche          3
audi             2
isuzu            2
jaguar           2
mazda            2
mercury          1
plymouth         1
toyota           1
Name: count, dtype: int64

In [44]:
# replace all "?" by nan
data.replace("?", np.nan, inplace=True)

In [48]:
'''
- bmw - remove missing values
- half of bmw rows are missing normalized-losses values
- despite some similar features, the engine size is larger, the power is greater compared to others, and higher prices 
'''
data.loc[data["make"]=="bmw"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
10,2,192,bmw,gas,std,2,sedan,rwd,front,101.2,...,ohc,four,108,mpfi,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,4,sedan,rwd,front,101.2,...,ohc,four,108,mpfi,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,2,sedan,rwd,front,101.2,...,ohc,six,164,mpfi,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,4,sedan,rwd,front,101.2,...,ohc,six,164,mpfi,9.0,121,4250,21,28,21105
14,1,NaN,bmw,gas,std,4,sedan,rwd,front,103.5,...,ohc,six,164,mpfi,9.0,121,4250,20,25,24565
15,0,NaN,bmw,gas,std,4,sedan,rwd,front,103.5,...,ohc,six,209,mpfi,8.0,182,5400,16,22,30760
16,0,NaN,bmw,gas,std,2,sedan,rwd,front,103.5,...,ohc,six,209,mpfi,8.0,182,5400,16,22,41315
17,0,NaN,bmw,gas,std,4,sedan,rwd,front,110.0,...,ohc,six,209,mpfi,8.0,182,5400,15,20,36880

In [226]:
'''
- peugot - remove missing values
- there is no wagon body-style with normalized-losses to compare
'''
data.loc[data["make"]=="peugot"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
107,0,161.0,peugot,gas,std,4,sedan,rwd,front,107.9,...,l,four,120,mpfi,8.4,97,5000,19,24,11900
108,0,161.0,peugot,diesel,turbo,4,sedan,rwd,front,107.9,...,l,four,152,idi,21.0,95,4150,28,33,13200
109,0,NaN,peugot,gas,std,4,wagon,rwd,front,114.2,...,l,four,120,mpfi,8.4,97,5000,19,24,12440
110,0,NaN,peugot,diesel,turbo,4,wagon,rwd,front,114.2,...,l,four,152,idi,21.0,95,4150,25,25,13860
111,0,161.0,peugot,gas,std,4,sedan,rwd,front,107.9,...,l,four,120,mpfi,8.4,95,5000,19,24,15580
112,0,161.0,peugot,diesel,turbo,4,sedan,rwd,front,107.9,...,l,four,152,idi,21.0,95,4150,28,33,16900
113,0,NaN,peugot,gas,std,4,wagon,rwd,front,114.2,...,l,four,120,mpfi,8.4,95,5000,19,24,16695
114,0,NaN,peugot,diesel,turbo,4,wagon,rwd,front,114.2,...,l,four,152,idi,21.0,95,4150,25,25,17075
115,0,161.0,peugot,gas,std,4,sedan,rwd,front,107.9,...,l,four,120,mpfi,8.4,97,5000,19,24,16630
116,0,161.0,peugot,diesel,turbo,4,sedan,rwd,front,107.9,...,l,four,152,idi,21.0,95,4150,28,33,17950
117,0,161.0,peugot,gas,turbo,4,sedan,rwd,front,108.0,...,l,four,134,mpfi,7.0,142,5600,18,24,18150

In [227]:
'''
- volkswagen - remove missing values
- the price and body-style are different from others to compare normalized-losses
'''
data.loc[data["make"]=="volkswagen"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
182,2,122.0,volkswagen,diesel,std,2,sedan,fwd,front,97.3,...,ohc,four,97,idi,23.0,52,4800,37,46,7775
183,2,122.0,volkswagen,gas,std,2,sedan,fwd,front,97.3,...,ohc,four,109,mpfi,9.0,85,5250,27,34,7975
184,2,94.0,volkswagen,diesel,std,4,sedan,fwd,front,97.3,...,ohc,four,97,idi,23.0,52,4800,37,46,7995
185,2,94.0,volkswagen,gas,std,4,sedan,fwd,front,97.3,...,ohc,four,109,mpfi,9.0,85,5250,27,34,8195
186,2,94.0,volkswagen,gas,std,4,sedan,fwd,front,97.3,...,ohc,four,109,mpfi,9.0,85,5250,27,34,8495
187,2,94.0,volkswagen,diesel,turbo,4,sedan,fwd,front,97.3,...,ohc,four,97,idi,23.0,68,4500,37,42,9495
188,2,94.0,volkswagen,gas,std,4,sedan,fwd,front,97.3,...,ohc,four,109,mpfi,10.0,100,5500,26,32,9995
189,3,NaN,volkswagen,gas,std,2,convertible,fwd,front,94.5,...,ohc,four,109,mpfi,8.5,90,5500,24,29,11595
190,3,256.0,volkswagen,gas,std,2,hatchback,fwd,front,94.5,...,ohc,four,109,mpfi,8.5,90,5500,24,29,9980
191,0,NaN,volkswagen,gas,std,4,sedan,fwd,front,100.4,...,ohc,five,136,mpfi,8.5,110,5500,19,24,13295
192,0,NaN,volkswagen,diesel,turbo,4,sedan,fwd,front,100.4,...,ohc,four,97,idi,23.0,68,4500,33,38,13845
193,0,NaN,volkswagen,gas,std,4,wagon,fwd,front,100.4,...,ohc,four,109,mpfi,9.0,88,5500,25,31,12290

In [228]:
'''
- alfa-romero - remove missing values
- no input value of normalized losses for this brand
'''
data.loc[data["make"]=="alfa-romero"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,2,convertible,rwd,front,88.6,...,dohc,four,130,mpfi,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,2,convertible,rwd,front,88.6,...,dohc,four,130,mpfi,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,2,hatchback,rwd,front,94.5,...,ohcv,six,152,mpfi,9.0,154,5000,19,26,16500

In [230]:
'''
- mercedes-benz - remove missing values
- there is no normalized-losses to compare with the same body-style, aspiration, and fuel-type
'''
data.loc[data["make"]=="mercedes-benz"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
67,-1,93.0,mercedes-benz,diesel,turbo,4,sedan,rwd,front,110.0,...,ohc,five,183,idi,21.5,123,4350,22,25,25552
68,-1,93.0,mercedes-benz,diesel,turbo,4,wagon,rwd,front,110.0,...,ohc,five,183,idi,21.5,123,4350,22,25,28248
69,0,93.0,mercedes-benz,diesel,turbo,2,hardtop,rwd,front,106.7,...,ohc,five,183,idi,21.5,123,4350,22,25,28176
70,-1,93.0,mercedes-benz,diesel,turbo,4,sedan,rwd,front,115.6,...,ohc,five,183,idi,21.5,123,4350,22,25,31600
71,-1,NaN,mercedes-benz,gas,std,4,sedan,rwd,front,115.6,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,34184
72,3,142.0,mercedes-benz,gas,std,2,convertible,rwd,front,96.6,...,ohcv,eight,234,mpfi,8.3,155,4750,16,18,35056
73,0,NaN,mercedes-benz,gas,std,4,sedan,rwd,front,120.9,...,ohcv,eight,308,mpfi,8.0,184,4500,14,16,40960
74,1,NaN,mercedes-benz,gas,std,2,hardtop,rwd,front,112.0,...,ohcv,eight,304,mpfi,8.0,184,4500,14,16,45400

In [234]:
'''
- mitsubishi - remove missing values
- there is a comparison value with the same fuel type, aspiration, number of doors, 
body style but with a smaller engine size and horsepower
'''
data.loc[data["make"]=="mitsubishi"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
76,2,161.0,mitsubishi,gas,std,2,hatchback,fwd,front,93.7,...,ohc,four,92,2bbl,9.4,68,5500,37,41,5389
77,2,161.0,mitsubishi,gas,std,2,hatchback,fwd,front,93.7,...,ohc,four,92,2bbl,9.4,68,5500,31,38,6189
78,2,161.0,mitsubishi,gas,std,2,hatchback,fwd,front,93.7,...,ohc,four,92,2bbl,9.4,68,5500,31,38,6669
79,1,161.0,mitsubishi,gas,turbo,2,hatchback,fwd,front,93.0,...,ohc,four,98,spdi,7.6,102,5500,24,30,7689
80,3,153.0,mitsubishi,gas,turbo,2,hatchback,fwd,front,96.3,...,ohc,four,110,spdi,7.5,116,5500,23,30,9959
81,3,153.0,mitsubishi,gas,std,2,hatchback,fwd,front,96.3,...,ohc,four,122,2bbl,8.5,88,5000,25,32,8499
82,3,NaN,mitsubishi,gas,turbo,2,hatchback,fwd,front,95.9,...,ohc,four,156,spdi,7.0,145,5000,19,24,12629
83,3,NaN,mitsubishi,gas,turbo,2,hatchback,fwd,front,95.9,...,ohc,four,156,spdi,7.0,145,5000,19,24,14869
84,3,NaN,mitsubishi,gas,turbo,2,hatchback,fwd,front,95.9,...,ohc,four,156,spdi,7.0,145,5000,19,24,14489
85,1,125.0,mitsubishi,gas,std,4,sedan,fwd,front,96.3,...,ohc,four,122,2bbl,8.5,88,5000,25,32,6989
86,1,125.0,mitsubishi,gas,std,4,sedan,fwd,front,96.3,...,ohc,four,122,2bbl,8.5,88,5000,25,32,8189
87,1,125.0,mitsubishi,gas,turbo,4,sedan,fwd,front,96.3,...,ohc,four,110,spdi,7.5,116,5500,23,30,9279
88,-1,137.0,mitsubishi,gas,std,4,sedan,fwd,front,96.3,...,ohc,four,110,spdi,7.5,116,5500,23,30,9279

In [235]:
'''
- porsche - remove missing values
- there is no normalized-losses to compare with the same body-style. just one input value
'''
data.loc[data["make"]=="porsche"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
125,3,186.0,porsche,gas,std,2,hatchback,rwd,front,94.5,...,ohc,four,151,mpfi,9.5,143,5500,19,27,22018
126,3,NaN,porsche,gas,std,2,hardtop,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,32528
127,3,NaN,porsche,gas,std,2,hardtop,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,34028
128,3,NaN,porsche,gas,std,2,convertible,rwd,rear,89.5,...,ohcf,six,194,mpfi,9.5,207,5900,17,25,37028

In [236]:
'''
# audi - remove missing values
# there is no normalized-losses to compare with the same body-style and num-of-doors 
'''
data.loc[data["make"]=="audi"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164.0,audi,gas,std,4,sedan,fwd,front,99.8,...,ohc,four,109,mpfi,10.0,102,5500,24,30,13950
4,2,164.0,audi,gas,std,4,sedan,4wd,front,99.4,...,ohc,five,136,mpfi,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,2,sedan,fwd,front,99.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,15250
6,1,158.0,audi,gas,std,4,sedan,fwd,front,105.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,4,wagon,fwd,front,105.8,...,ohc,five,136,mpfi,8.5,110,5500,19,25,18920
8,1,158.0,audi,gas,turbo,4,sedan,fwd,front,105.8,...,ohc,five,131,mpfi,8.3,140,5500,17,20,23875

In [237]:
'''
# isuzu - remove missing values
# there is no normalized-losses to compare - there will no longer be the isuzu brand in the dataset
'''
data.loc[data["make"]=="isuzu"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
43,0,NaN,isuzu,gas,std,4,sedan,rwd,front,94.3,...,ohc,four,111,2bbl,8.5,78,4800,24,29,6785
46,2,NaN,isuzu,gas,std,2,hatchback,rwd,front,96.0,...,ohc,four,119,spfi,9.2,90,5000,24,29,11048

In [238]:
'''
- jaguar
- in the second, the same normalized loss available was added due to having similar resources 
to the first data available. The last one will be removed as it does not fit in with the other 
available vehicles from the Jaguar brand
'''
data.loc[data["make"]=="jaguar"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
47,0,145.0,jaguar,gas,std,4,sedan,rwd,front,113.0,...,dohc,six,258,mpfi,8.1,176,4750,15,19,32250
48,0,NaN,jaguar,gas,std,4,sedan,rwd,front,113.0,...,dohc,six,258,mpfi,8.1,176,4750,15,19,35550
49,0,NaN,jaguar,gas,std,2,sedan,rwd,front,102.0,...,ohcv,twelve,326,mpfi,11.5,262,5000,13,17,36000

In [55]:
# get the normalized_losses value
value_losses = data.loc[(data["make"]=="jaguar")&(data.index == 47)]["normalized-losses"]

In [76]:
# replace 
data.loc[(data["make"]=="jaguar")&(data.index == 48), "normalized-losses"] = value_losses.iloc[0]

In [79]:
data.loc[data["make"]=="jaguar"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
47,0,145,jaguar,gas,std,4,sedan,rwd,front,113.0,...,dohc,six,258,mpfi,8.1,176,4750,15,19,32250
48,0,145,jaguar,gas,std,4,sedan,rwd,front,113.0,...,dohc,six,258,mpfi,8.1,176,4750,15,19,35550
49,0,NaN,jaguar,gas,std,2,sedan,rwd,front,102.0,...,ohcv,twelve,326,mpfi,11.5,262,5000,13,17,36000

In [239]:
'''
- mazda - remove missing values
- no values to compare with the same fuel-type
'''
data.loc[data["make"]=="mazda"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
50,1,104.0,mazda,gas,std,2,hatchback,fwd,front,93.1,...,ohc,four,91,2bbl,9.0,68,5000,30,31,5195
51,1,104.0,mazda,gas,std,2,hatchback,fwd,front,93.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6095
52,1,104.0,mazda,gas,std,2,hatchback,fwd,front,93.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6795
53,1,113.0,mazda,gas,std,4,sedan,fwd,front,93.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,6695
54,1,113.0,mazda,gas,std,4,sedan,fwd,front,93.1,...,ohc,four,91,2bbl,9.0,68,5000,31,38,7395
55,3,150.0,mazda,gas,std,2,hatchback,rwd,front,95.3,...,rotor,two,70,4bbl,9.4,101,6000,17,23,10945
56,3,150.0,mazda,gas,std,2,hatchback,rwd,front,95.3,...,rotor,two,70,4bbl,9.4,101,6000,17,23,11845
57,3,150.0,mazda,gas,std,2,hatchback,rwd,front,95.3,...,rotor,two,70,4bbl,9.4,101,6000,17,23,13645
58,3,150.0,mazda,gas,std,2,hatchback,rwd,front,95.3,...,rotor,two,80,mpfi,9.4,135,6000,16,23,15645
59,1,129.0,mazda,gas,std,2,hatchback,fwd,front,98.8,...,ohc,four,122,2bbl,8.6,84,4800,26,32,8845
60,0,115.0,mazda,gas,std,4,sedan,fwd,front,98.8,...,ohc,four,122,2bbl,8.6,84,4800,26,32,8495
61,1,129.0,mazda,gas,std,2,hatchback,fwd,front,98.8,...,ohc,four,122,2bbl,8.6,84,4800,26,32,10595
62,0,115.0,mazda,gas,std,4,sedan,fwd,front,98.8,...,ohc,four,122,2bbl,8.6,84,4800,26,32,10245
63,0,NaN,mazda,diesel,std,4,sedan,fwd,front,98.8,...,ohc,four,122,idi,22.7,64,4650,36,42,10795
64,0,115.0,mazda,gas,std,4,hatchback,fwd,front,98.8,...,ohc,four,122,2bbl,8.6,84,4800,26,32,11245
65,0,118.0,mazda,gas,std,4,sedan,rwd,front,104.9,...,ohc,four,140,mpfi,8.0,120,5000,19,27,18280
66,0,NaN,mazda,diesel,std,4,sedan,rwd,front,104.9,...,ohc,four,134,idi,22.0,72,4200,31,39,18344

In [240]:
'''
- mercury - remove missing values
- no values to compare with the same make
'''
data.loc[data["make"]=="mercury"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
75,1,NaN,mercury,gas,turbo,2,hatchback,rwd,front,102.7,...,ohc,four,140,mpfi,8.0,175,5000,19,24,16503

In [241]:
'''
- plymouth - remove missing values
- The one with the greatest risk. There's no way to compare it to others
'''
data.loc[data["make"]=="plymouth"]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
118,1,119.0,plymouth,gas,std,2,hatchback,fwd,front,93.7,...,ohc,four,90,2bbl,9.4,68,5500,37,41,5572
119,1,119.0,plymouth,gas,turbo,2,hatchback,fwd,front,93.7,...,ohc,four,98,spdi,7.6,102,5500,24,30,7957
120,1,154.0,plymouth,gas,std,4,hatchback,fwd,front,93.7,...,ohc,four,90,2bbl,9.4,68,5500,31,38,6229
121,1,154.0,plymouth,gas,std,4,sedan,fwd,front,93.7,...,ohc,four,90,2bbl,9.4,68,5500,31,38,6692
122,1,154.0,plymouth,gas,std,4,sedan,fwd,front,93.7,...,ohc,four,98,2bbl,9.4,68,5500,31,38,7609
123,-1,74.0,plymouth,gas,std,4,wagon,fwd,front,103.3,...,ohc,four,122,2bbl,8.5,88,5000,24,30,8921
124,3,NaN,plymouth,gas,turbo,2,hatchback,rwd,front,95.9,...,ohc,four,156,spdi,7.0,145,5000,19,24,12764

In [82]:
data.loc[data["make"]=="toyota"].tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
177,-1,65,toyota,gas,std,4,hatchback,fwd,front,102.4,...,ohc,four,122,mpfi,8.7,92,4200,27,32,11248
178,3,197,toyota,gas,std,2,hatchback,rwd,front,102.9,...,dohc,six,171,mpfi,9.3,161,5200,20,24,16558
179,3,197,toyota,gas,std,2,hatchback,rwd,front,102.9,...,dohc,six,171,mpfi,9.3,161,5200,19,24,15998
180,-1,90,toyota,gas,std,4,sedan,rwd,front,104.5,...,dohc,six,171,mpfi,9.2,156,5200,20,24,15690
181,-1,NaN,toyota,gas,std,4,wagon,rwd,front,104.5,...,dohc,six,161,mpfi,9.2,156,5200,19,24,15750

In [81]:
# remove missing values
# there are similar features, but differs in wheel-base, engine-type, number-of-cylinders, engine-size, and horsepower
data.loc[(data["make"]=="toyota")&(data["body-style"]=="wagon")]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-type,num-of-cylinders,engine-size,fuel-system,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
153,0,77,toyota,gas,std,4,wagon,fwd,front,95.7,...,ohc,four,92,2bbl,9.0,62,4800,31,37,6918
154,0,81,toyota,gas,std,4,wagon,4wd,front,95.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,7898
155,0,91,toyota,gas,std,4,wagon,4wd,front,95.7,...,ohc,four,92,2bbl,9.0,62,4800,27,32,8778
181,-1,NaN,toyota,gas,std,4,wagon,rwd,front,104.5,...,dohc,six,161,mpfi,9.2,156,5200,19,24,15750

In [88]:
# drop missing values from normalized-losses column
data = data.dropna(subset=['normalized-losses'])

In [90]:
# check if there is any missing value left 
data.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [91]:
# check data types and what was supposed to be in numeric format
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 165 entries, 3 to 204
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          165 non-null    int64
 1   normalized-losses  165 non-null    object
 2   make               165 non-null    object
 3   fuel-type          165 non-null    object
 4   aspiration         165 non-null    object
 5   num-of-doors       165 non-null    int64
 6   body-style         165 non-null    object
 7   drive-wheels       165 non-null    object
 8   engine-location    165 non-null    object
 9   wheel-base         165 non-null    float64
 10  length             165 non-null    float64
 11  width              165 non-null    float64
 12  height             165 non-null    float64
 13  curb-weight        165 non-null    int64
 14  engine-type        165 non-null    object
 15  num-of-cylinders   165 non-null    object
 16  engine-size        165 non-null    int64
 17  fuel-system        165 non-null    object
 18  compression-ratio  165 non-null    float64
 19  horsepower         165 non-null    object
 20  peak-rpm           165 non-null    object
 21  city-mpg           165 non-null    int64
 22  highway-mpg        165 non-null    int64
 23  price              165 non-null    object
dtypes: float64(5), int64(6), object(13)
memory usage: 32.2+ KB

- columns that need to fix the format type: normalized-losses, num-of-cylinders, horsepower, peak-rpm, and price

In [94]:
def calc_num_cylinders(cylstr):
    cyls = {'two':2,'three':3,'four':4,'five':5,'six':6,'eight':8,'twelve':12}
    if(cylstr in cyls.keys()):
        return cyls[cylstr]
    return 0

# change the num-of-cylinders column to numeric format
data['num-of-cylinders'] = data['num-of-cylinders'].apply(lambda x: calc_num_cylinders(x))

In [97]:
# Fix data with incorrect types 
data['normalized-losses'] = pd.to_numeric(data['normalized-losses'], errors='coerce')
data['horsepower'] = pd.to_numeric(data['horsepower'], errors='coerce')
data['peak-rpm'] = pd.to_numeric(data['peak-rpm'], errors='coerce')
data['price'] = pd.to_numeric(data['price'], errors='coerce')

In [99]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 165 entries, 3 to 204
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          165 non-null    int64
 1   normalized-losses  165 non-null    int64
 2   make               165 non-null    object
 3   fuel-type          165 non-null    object
 4   aspiration         165 non-null    object
 5   num-of-doors       165 non-null    int64
 6   body-style         165 non-null    object
 7   drive-wheels       165 non-null    object
 8   engine-location    165 non-null    object
 9   wheel-base         165 non-null    float64
 10  length             165 non-null    float64
 11  width              165 non-null    float64
 12  height             165 non-null    float64
 13  curb-weight        165 non-null    int64
 14  engine-type        165 non-null    object
 15  num-of-cylinders   165 non-null    int64
 16  engine-size        165 non-null    int64
 17  fuel-system        165 non-null    object
 18  compression-ratio  165 non-null    float64
 19  horsepower         165 non-null    int64
 20  peak-rpm           165 non-null    int64
 21  city-mpg           165 non-null    int64
 22  highway-mpg        165 non-null    int64
 23  price              165 non-null    int64
dtypes: float64(5), int64(11), object(8)
memory usage: 32.2+ KB

In [101]:
# save cleaned data to csv file
data.to_csv('clean_data.csv', index=False)